name: SpawnPlugin
version: 1.0
main: dev.amargos.SpawnPlugin
api-version: 1.13
author: Amargos
commands:
  setspawn:
    description: Set the server spawn location
    usage: /<command>
  delspawn:
    description: Delete the configured spawn location
    usage: /<command>
  spawn:
    description: Teleport to the configured spawn
    usage: /<command>
  spawnreload:
    description: Reload the plugin configuration
    usage: /<command>
permissions:
  spawnplugin.set:
    description: Allows settings the spawn
    default: op
  spawnplugin.del:
    description: Allows deleting the spawn
    default: op
  spawnplugin.spawn:
    description: Allows teleporting to spawn
    default: true
  spawnplugin.reload:
    description: Allows reloading the plugin configuration
    default: op